// ALL PRODUCTS

const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

// SINGLE PRODUCT

const PRODUCT_SINGLE_REQUEST = 'PRODUCT_SINGLE_REQUEST';
const PRODUCT_SINGLE_SUCCESS = 'PRODUCT_SINGLE_SUCCESS';
const PRODUCT_SINGLE_FAIL = 'PRODUCT_SINGLE_FAIL';

// 	DELETE PRODUCT

const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';

// CREATE PRODUCT

const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST';
const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL';
const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET';

// UPDATE PRODUCT

const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';
const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET';

// REVIEW PRODUCT

const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST';
const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS';
const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL';
const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET';

// CART

const ADDED_TO_CART = 'ADDED_TO_CART';
const REMOVED_FROM_CART = 'REMOVED_FROM_CART';
const CLEAR_CART = 'CLEAR_CART';

// PAYMENT PROCCESS

const SHIPPING_ADDRESS = 'SHIPPING_ADDRESS';
const PAYMENT_METHOD = 'PAYMENT_METHOD';

// USER AUTHENTICATION

const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
const USER_LOGOUT = 'USER_LOGOUT';

// CREATE USER

const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

// GET USER PROFILE

const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';

// GET ALL USERS PROFILE FOR ADMIN

const USERS_LIST_REQUEST = 'USERS_LIST_REQUEST';
const USERS_LIST_SUCCESS = 'USERS_LIST_SUCCESS';
const USERS_LIST_FAIL = 'USERS_LIST_FAIL';
const USERS_LIST_RESET = 'USERS_LIST_RESET';

// DELETE USERS PROFILE
const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

// UPDATE USER PROFILE

const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
const USER_UPDATE_RESET = 'USER_UPDATE_RESET';

// 	ORDER CREATE

const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';

// 	ORDER DETAILS

const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';
const ORDER_DETAILS_RESET = 'ORDER_DETAILS_RESET';

// ADMIN ORDER DETAILS

const ORDERS_ADMIN_REQUEST = 'ORDERS_ADMIN_REQUEST';
const ORDERS_ADMIN_SUCCESS = 'ORDERS_ADMIN_SUCCESS';
const ORDERS_ADMIN_FAIL = 'ORDERS_ADMIN_FAIL';
const ORDERS_ADMIN_RESET = 'ORDERS_ADMIN_RESET';

// 	ORDER PAY

const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

// 	ORDER DELIVER

const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST';
const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS';
const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL';
const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET';

// 	ORDER CREATE

const MY_ORDER_REQUEST = 'MY_ORDER_REQUEST';
const MY_ORDER_SUCCESS = 'MY_ORDER_SUCCESS';
const MY_ORDER_FAIL = 'MY_ORDER_FAIL';
const MY_ORDER_RESET = 'MY_ORDER_RESET';

export {
	PRODUCT_LIST_REQUEST,
	PRODUCT_LIST_SUCCESS,
	PRODUCT_LIST_FAIL,
	ORDER_CREATE_REQUEST,
	ORDER_CREATE_SUCCESS,
	ORDER_CREATE_FAIL,
	ORDER_DETAILS_REQUEST,
	ORDER_DETAILS_SUCCESS,
	ORDER_DETAILS_FAIL,
	ORDER_DETAILS_RESET,
	ORDERS_ADMIN_REQUEST,
	ORDERS_ADMIN_SUCCESS,
	ORDERS_ADMIN_FAIL,
	ORDERS_ADMIN_RESET,
	ORDER_PAY_REQUEST,
	ORDER_PAY_SUCCESS,
	ORDER_PAY_FAIL,
	ORDER_PAY_RESET,
	PRODUCT_SINGLE_REQUEST,
	PRODUCT_SINGLE_SUCCESS,
	PRODUCT_SINGLE_FAIL,
	PRODUCT_DELETE_REQUEST,
	PRODUCT_DELETE_SUCCESS,
	PRODUCT_DELETE_FAIL,
	PRODUCT_UPDATE_REQUEST,
	PRODUCT_UPDATE_SUCCESS,
	PRODUCT_UPDATE_FAIL,
	PRODUCT_UPDATE_RESET,
	PRODUCT_CREATE_REVIEW_REQUEST,
	PRODUCT_CREATE_REVIEW_SUCCESS,
	PRODUCT_CREATE_REVIEW_FAIL,
	PRODUCT_CREATE_REVIEW_RESET,
	ADDED_TO_CART,
	CLEAR_CART,
	SHIPPING_ADDRESS,
	REMOVED_FROM_CART,
	USER_LOGIN_REQUEST,
	USER_LOGIN_SUCCESS,
	USER_LOGIN_FAIL,
	USER_REGISTER_REQUEST,
	USER_REGISTER_SUCCESS,
	USER_REGISTER_FAIL,
	USER_DETAILS_REQUEST,
	USER_DETAILS_SUCCESS,
	USER_DETAILS_FAIL,
	USER_UPDATE_REQUEST,
	USER_UPDATE_SUCCESS,
	USER_UPDATE_FAIL,
	USER_UPDATE_RESET,
	USER_LOGOUT,
	PAYMENT_METHOD,
	MY_ORDER_REQUEST,
	MY_ORDER_SUCCESS,
	MY_ORDER_FAIL,
	MY_ORDER_RESET,
	USERS_LIST_REQUEST,
	USERS_LIST_SUCCESS,
	USERS_LIST_FAIL,
	USERS_LIST_RESET,
	DELETE_USER_REQUEST,
	DELETE_USER_SUCCESS,
	DELETE_USER_FAIL,
	PRODUCT_CREATE_REQUEST,
	PRODUCT_CREATE_SUCCESS,
	PRODUCT_CREATE_FAIL,
	PRODUCT_CREATE_RESET,
	ORDER_DELIVER_REQUEST,
	ORDER_DELIVER_SUCCESS,
	ORDER_DELIVER_FAIL,
	ORDER_DELIVER_RESET,
};
