// all products

const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

// single product

const PRODUCT_SINGLE_REQUEST = "PRODUCT_SINGLE_REQUEST";
const PRODUCT_SINGLE_SUCCESS = "PRODUCT_SINGLE_SUCCESS";
const PRODUCT_SINGLE_FAIL = "PRODUCT_SINGLE_FAIL";

// add to cart

const ADDED_TO_CART = "ADDED_TO_CART";
const REMOVED_FROM_CART = "REMOVED_FROM_CART";

// user AUTH

const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
const USER_LOGOUT = 'USER_LOGOUT'

export {
  PRODUCT_LIST_REQUEST,
  PRODUCT_LIST_SUCCESS,
  PRODUCT_LIST_FAIL,
  PRODUCT_SINGLE_REQUEST,
  PRODUCT_SINGLE_SUCCESS,
  PRODUCT_SINGLE_FAIL,
  ADDED_TO_CART,
  REMOVED_FROM_CART,
  USER_LOGIN_REQUEST,
  USER_LOGIN_SUCCESS,
  USER_LOGIN_FAIL,
  USER_LOGOUT
};
