// ALL PRODUCTS

const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

// SINGLE PRODUCT

const PRODUCT_SINGLE_REQUEST = 'PRODUCT_SINGLE_REQUEST';
const PRODUCT_SINGLE_SUCCESS = 'PRODUCT_SINGLE_SUCCESS';
const PRODUCT_SINGLE_FAIL = 'PRODUCT_SINGLE_FAIL';

// ADD TO CART

const ADDED_TO_CART = 'ADDED_TO_CART';
const REMOVED_FROM_CART = 'REMOVED_FROM_CART';

// PAYMENT PROCCESS

const SHIPPING_ADDRESS = 'SHIPPING_ADDRESS';
const PAYMENT_METHOD = 'PAYMENT_METHOD';

// USER AUTHENTICATION

const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
const USER_LOGOUT = 'USER_LOGOUT';

// CREATE USER

const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

// GET USER PROFILE

const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';

// UPDATE USER PROFILE

const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
const USER_UPDATE_RESET = 'USER_UPDATE_RESET';

// 	ORDER CREATE

const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';

// 	ORDER DETAILS

const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

// 	ORDER PAY

const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

// 	ORDER CREATE

const MY_ORDER_REQUEST = 'MY_ORDER_REQUEST';
const MY_ORDER_SUCCESS = 'MY_ORDER_SUCCESS';
const MY_ORDER_FAIL = 'MY_ORDER_FAIL';
const MY_ORDER_RESET = 'MY_ORDER_RESET';

export {
	PRODUCT_LIST_REQUEST,
	PRODUCT_LIST_SUCCESS,
	PRODUCT_LIST_FAIL,
	ORDER_CREATE_REQUEST,
	ORDER_CREATE_SUCCESS,
	ORDER_CREATE_FAIL,
	ORDER_DETAILS_REQUEST,
	ORDER_DETAILS_SUCCESS,
	ORDER_DETAILS_FAIL,
	ORDER_PAY_REQUEST,
	ORDER_PAY_SUCCESS,
	ORDER_PAY_FAIL,
	ORDER_PAY_RESET,
	PRODUCT_SINGLE_REQUEST,
	PRODUCT_SINGLE_SUCCESS,
	PRODUCT_SINGLE_FAIL,
	ADDED_TO_CART,
	SHIPPING_ADDRESS,
	REMOVED_FROM_CART,
	USER_LOGIN_REQUEST,
	USER_LOGIN_SUCCESS,
	USER_LOGIN_FAIL,
	USER_REGISTER_REQUEST,
	USER_REGISTER_SUCCESS,
	USER_REGISTER_FAIL,
	USER_DETAILS_REQUEST,
	USER_DETAILS_SUCCESS,
	USER_DETAILS_FAIL,
	USER_UPDATE_REQUEST,
	USER_UPDATE_SUCCESS,
	USER_UPDATE_FAIL,
	USER_UPDATE_RESET,
	USER_LOGOUT,
	PAYMENT_METHOD,
	MY_ORDER_REQUEST,
	MY_ORDER_SUCCESS,
	MY_ORDER_FAIL,
	MY_ORDER_RESET,
};
